# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'seam_carving_guihMACsS.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(908, 709)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.act_open = QAction(MainWindow)
        self.act_open.setObjectName(u"act_open")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(800, 549))
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.wg_img = QWidget(self.centralwidget)
        self.wg_img.setObjectName(u"wg_img")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.wg_img.sizePolicy().hasHeightForWidth())
        self.wg_img.setSizePolicy(sizePolicy2)
        self.lb_img = QLabel(self.wg_img)
        self.lb_img.setObjectName(u"lb_img")
        self.lb_img.setGeometry(QRect(0, 0, 351, 231))
        sizePolicy3 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.lb_img.sizePolicy().hasHeightForWidth())
        self.lb_img.setSizePolicy(sizePolicy3)
        self.lb_img.setMinimumSize(QSize(0, 0))
        self.lb_img.setFrameShape(QFrame.NoFrame)
        self.lb_img.setTextFormat(Qt.AutoText)
        self.lb_img.setScaledContents(False)
        self.lb_img.setAlignment(Qt.AlignCenter)
        self.lb_img.setMargin(10)
        self.graphicsView = QGraphicsView(self.wg_img)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(140, 170, 256, 192))

        self.horizontalLayout_2.addWidget(self.wg_img)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy4)
        self.frame.setMinimumSize(QSize(240, 560))
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 11)
        self.groupBox_5 = QGroupBox(self.frame)
        self.groupBox_5.setObjectName(u"groupBox_5")
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy5)
        self.groupBox_5.setMinimumSize(QSize(220, 60))
        self.groupBox_5.setMaximumSize(QSize(221, 80))
        self.horizontalLayout = QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.bt_open = QPushButton(self.groupBox_5)
        self.bt_open.setObjectName(u"bt_open")

        self.horizontalLayout.addWidget(self.bt_open)

        self.bt_run = QPushButton(self.groupBox_5)
        self.bt_run.setObjectName(u"bt_run")
        sizePolicy6 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.bt_run.sizePolicy().hasHeightForWidth())
        self.bt_run.setSizePolicy(sizePolicy6)

        self.horizontalLayout.addWidget(self.bt_run)

        self.bt_save = QPushButton(self.groupBox_5)
        self.bt_save.setObjectName(u"bt_save")

        self.horizontalLayout.addWidget(self.bt_save)


        self.verticalLayout_3.addWidget(self.groupBox_5)

        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        sizePolicy5.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy5)
        self.groupBox_2.setMinimumSize(QSize(220, 168))
        self.bt_clr = QPushButton(self.groupBox_2)
        self.bt_clr.setObjectName(u"bt_clr")
        self.bt_clr.setGeometry(QRect(150, 120, 61, 28))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 60, 91, 16))
        self.sb_size = QSpinBox(self.groupBox_2)
        self.sb_size.setObjectName(u"sb_size")
        self.sb_size.setGeometry(QRect(140, 60, 51, 22))
        self.bt_undo = QPushButton(self.groupBox_2)
        self.bt_undo.setObjectName(u"bt_undo")
        self.bt_undo.setGeometry(QRect(10, 120, 51, 28))
        self.rd_protect = QRadioButton(self.groupBox_2)
        self.rd_protect.setObjectName(u"rd_protect")
        self.rd_protect.setGeometry(QRect(20, 20, 71, 20))
        self.rd_remove = QRadioButton(self.groupBox_2)
        self.rd_remove.setObjectName(u"rd_remove")
        self.rd_remove.setGeometry(QRect(120, 20, 71, 20))
        self.bt_redo = QPushButton(self.groupBox_2)
        self.bt_redo.setObjectName(u"bt_redo")
        self.bt_redo.setGeometry(QRect(80, 120, 51, 28))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 90, 81, 16))
        self.sb_weight = QSpinBox(self.groupBox_2)
        self.sb_weight.setObjectName(u"sb_weight")
        self.sb_weight.setGeometry(QRect(140, 90, 51, 22))

        self.verticalLayout_3.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy5.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy5)
        self.groupBox_3.setMinimumSize(QSize(220, 140))
        self.sb_rows = QSpinBox(self.groupBox_3)
        self.sb_rows.setObjectName(u"sb_rows")
        self.sb_rows.setGeometry(QRect(40, 30, 51, 22))
        self.sb_rows.setMinimum(-999999)
        self.sb_rows.setMaximum(999999)
        self.sb_rows.setValue(0)
        self.sb_cols = QSpinBox(self.groupBox_3)
        self.sb_cols.setObjectName(u"sb_cols")
        self.sb_cols.setGeometry(QRect(160, 30, 51, 22))
        self.sb_cols.setMinimum(-999999)
        self.sb_cols.setMaximum(999999)
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 30, 51, 16))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 31, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 70, 41, 16))
        self.cmb_mode = QComboBox(self.groupBox_3)
        self.cmb_mode.addItem("")
        self.cmb_mode.addItem("")
        self.cmb_mode.setObjectName(u"cmb_mode")
        self.cmb_mode.setGeometry(QRect(110, 70, 101, 22))
        self.ckb_vis = QCheckBox(self.groupBox_3)
        self.ckb_vis.setObjectName(u"ckb_vis")
        self.ckb_vis.setGeometry(QRect(40, 110, 151, 20))

        self.verticalLayout_3.addWidget(self.groupBox_3)

        self.groupBox_4 = QGroupBox(self.frame)
        self.groupBox_4.setObjectName(u"groupBox_4")
        sizePolicy7 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy7)
        self.groupBox_4.setMinimumSize(QSize(220, 140))
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.scr_area = QScrollArea(self.groupBox_4)
        self.scr_area.setObjectName(u"scr_area")
        self.scr_area.setFrameShape(QFrame.NoFrame)
        self.scr_area.setLineWidth(1)
        self.scr_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scr_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 218, 244))
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.lb_infor = QLabel(self.scrollAreaWidgetContents)
        self.lb_infor.setObjectName(u"lb_infor")
        self.lb_infor.setLayoutDirection(Qt.LeftToRight)
        self.lb_infor.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lb_infor.setWordWrap(True)
        self.lb_infor.setMargin(10)

        self.verticalLayout.addWidget(self.lb_infor)

        self.scr_area.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_2.addWidget(self.scr_area)


        self.verticalLayout_3.addWidget(self.groupBox_4)


        self.horizontalLayout_2.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 908, 26))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.act_open.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.act_open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.lb_img.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Action", None))
        self.bt_open.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.bt_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.bt_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Mask", None))
        self.bt_clr.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Brush radius", None))
        self.bt_undo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.rd_protect.setText(QCoreApplication.translate("MainWindow", u"Protect", None))
        self.rd_remove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.bt_redo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Important", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Seam number", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Column", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Row", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.cmb_mode.setItemText(0, QCoreApplication.translate("MainWindow", u"Forward", None))
        self.cmb_mode.setItemText(1, QCoreApplication.translate("MainWindow", u"Backward", None))

        self.ckb_vis.setText(QCoreApplication.translate("MainWindow", u"visualize the process", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Information", None))
        self.lb_infor.setText(QCoreApplication.translate("MainWindow", u"Welcome to SeamCarving", None))
    # retranslateUi

