# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'seam_carving_gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(908, 709)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.act_open = QAction(MainWindow)
        self.act_open.setObjectName(u"act_open")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(800, 549))
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.wg_img = QWidget(self.centralwidget)
        self.wg_img.setObjectName(u"wg_img")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.wg_img.sizePolicy().hasHeightForWidth())
        self.wg_img.setSizePolicy(sizePolicy2)
        self.lb_img = QLabel(self.wg_img)
        self.lb_img.setObjectName(u"lb_img")
        self.lb_img.setGeometry(QRect(0, 0, 461, 291))
        sizePolicy3 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.lb_img.sizePolicy().hasHeightForWidth())
        self.lb_img.setSizePolicy(sizePolicy3)
        self.lb_img.setMinimumSize(QSize(0, 0))
        self.lb_img.setFrameShape(QFrame.NoFrame)
        self.lb_img.setLineWidth(1)
        self.lb_img.setTextFormat(Qt.AutoText)
        self.lb_img.setScaledContents(False)
        self.lb_img.setAlignment(Qt.AlignCenter)
        self.lb_img.setMargin(10)
        self.lb_mask = QLabel(self.wg_img)
        self.lb_mask.setObjectName(u"lb_mask")
        self.lb_mask.setGeometry(QRect(0, 0, 281, 171))

        self.horizontalLayout_2.addWidget(self.wg_img)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy4)
        self.frame.setMinimumSize(QSize(240, 560))
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(-1, 5, -1, 11)
        self.groupBox_5 = QGroupBox(self.frame)
        self.groupBox_5.setObjectName(u"groupBox_5")
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy5)
        self.groupBox_5.setMinimumSize(QSize(220, 60))
        self.groupBox_5.setMaximumSize(QSize(221, 80))
        self.horizontalLayout = QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.bt_open = QPushButton(self.groupBox_5)
        self.bt_open.setObjectName(u"bt_open")

        self.horizontalLayout.addWidget(self.bt_open)

        self.bt_run = QPushButton(self.groupBox_5)
        self.bt_run.setObjectName(u"bt_run")
        sizePolicy6 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.bt_run.sizePolicy().hasHeightForWidth())
        self.bt_run.setSizePolicy(sizePolicy6)

        self.horizontalLayout.addWidget(self.bt_run)

        self.bt_save = QPushButton(self.groupBox_5)
        self.bt_save.setObjectName(u"bt_save")

        self.horizontalLayout.addWidget(self.bt_save)


        self.verticalLayout_3.addWidget(self.groupBox_5)

        self.gb_mask = QGroupBox(self.frame)
        self.gb_mask.setObjectName(u"gb_mask")
        self.gb_mask.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.gb_mask.sizePolicy().hasHeightForWidth())
        self.gb_mask.setSizePolicy(sizePolicy5)
        self.gb_mask.setMinimumSize(QSize(220, 150))
        self.bt_clr = QPushButton(self.gb_mask)
        self.bt_clr.setObjectName(u"bt_clr")
        self.bt_clr.setGeometry(QRect(120, 110, 81, 28))
        self.label = QLabel(self.gb_mask)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 80, 91, 16))
        self.sb_size = QSpinBox(self.gb_mask)
        self.sb_size.setObjectName(u"sb_size")
        self.sb_size.setGeometry(QRect(140, 80, 51, 18))
        self.sb_size.setMinimum(5)
        self.sb_size.setMaximum(40)
        self.sb_size.setSingleStep(5)
        self.sb_size.setValue(15)
        self.bt_undo = QPushButton(self.gb_mask)
        self.bt_undo.setObjectName(u"bt_undo")
        self.bt_undo.setGeometry(QRect(20, 110, 81, 28))
        self.ckb_protect = QCheckBox(self.gb_mask)
        self.ckb_protect.setObjectName(u"ckb_protect")
        self.ckb_protect.setGeometry(QRect(20, 20, 71, 20))
        self.ckb_remove = QCheckBox(self.gb_mask)
        self.ckb_remove.setObjectName(u"ckb_remove")
        self.ckb_remove.setGeometry(QRect(120, 20, 71, 20))
        self.ckb_hremove = QCheckBox(self.gb_mask)
        self.ckb_hremove.setObjectName(u"ckb_hremove")
        self.ckb_hremove.setGeometry(QRect(20, 50, 191, 20))

        self.verticalLayout_3.addWidget(self.gb_mask)

        self.gb_seam = QGroupBox(self.frame)
        self.gb_seam.setObjectName(u"gb_seam")
        self.gb_seam.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.gb_seam.sizePolicy().hasHeightForWidth())
        self.gb_seam.setSizePolicy(sizePolicy5)
        self.gb_seam.setMinimumSize(QSize(220, 90))
        self.sb_rows = QSpinBox(self.gb_seam)
        self.sb_rows.setObjectName(u"sb_rows")
        self.sb_rows.setGeometry(QRect(40, 30, 51, 18))
        self.sb_rows.setMinimum(-999999)
        self.sb_rows.setMaximum(999999)
        self.sb_rows.setValue(0)
        self.sb_cols = QSpinBox(self.gb_seam)
        self.sb_cols.setObjectName(u"sb_cols")
        self.sb_cols.setGeometry(QRect(160, 30, 51, 18))
        self.sb_cols.setMinimum(-999999)
        self.sb_cols.setMaximum(999999)
        self.label_2 = QLabel(self.gb_seam)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 30, 51, 16))
        self.label_3 = QLabel(self.gb_seam)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 31, 16))
        self.label_5 = QLabel(self.gb_seam)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 62, 41, 16))
        self.cmb_mode = QComboBox(self.gb_seam)
        self.cmb_mode.addItem("")
        self.cmb_mode.addItem("")
        self.cmb_mode.setObjectName(u"cmb_mode")
        self.cmb_mode.setGeometry(QRect(110, 60, 101, 22))

        self.verticalLayout_3.addWidget(self.gb_seam)

        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(0, 70))
        self.ckb_process = QCheckBox(self.groupBox)
        self.ckb_process.setObjectName(u"ckb_process")
        self.ckb_process.setGeometry(QRect(20, 20, 71, 20))
        self.ckb_energy_map = QCheckBox(self.groupBox)
        self.ckb_energy_map.setObjectName(u"ckb_energy_map")
        self.ckb_energy_map.setGeometry(QRect(110, 20, 101, 20))
        self.ckb_mask = QCheckBox(self.groupBox)
        self.ckb_mask.setObjectName(u"ckb_mask")
        self.ckb_mask.setGeometry(QRect(20, 40, 61, 20))
        self.ckb_all_seam = QCheckBox(self.groupBox)
        self.ckb_all_seam.setObjectName(u"ckb_all_seam")
        self.ckb_all_seam.setGeometry(QRect(110, 40, 81, 20))

        self.verticalLayout_3.addWidget(self.groupBox)

        self.groupBox_4 = QGroupBox(self.frame)
        self.groupBox_4.setObjectName(u"groupBox_4")
        sizePolicy7 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy7)
        self.groupBox_4.setMinimumSize(QSize(220, 140))
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.scr_area = QScrollArea(self.groupBox_4)
        self.scr_area.setObjectName(u"scr_area")
        self.scr_area.setFrameShape(QFrame.NoFrame)
        self.scr_area.setLineWidth(1)
        self.scr_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scr_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 218, 241))
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(10, 5, 10, 5)
        self.lb_infor = QLabel(self.scrollAreaWidgetContents)
        self.lb_infor.setObjectName(u"lb_infor")
        self.lb_infor.setLayoutDirection(Qt.LeftToRight)
        self.lb_infor.setFrameShape(QFrame.NoFrame)
        self.lb_infor.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lb_infor.setWordWrap(True)
        self.lb_infor.setMargin(0)

        self.verticalLayout.addWidget(self.lb_infor)

        self.scr_area.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_2.addWidget(self.scr_area)


        self.verticalLayout_3.addWidget(self.groupBox_4)


        self.horizontalLayout_2.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 908, 26))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.act_open.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.act_open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.lb_img.setText("")
        self.lb_mask.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Action", None))
        self.bt_open.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.bt_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.bt_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.gb_mask.setTitle(QCoreApplication.translate("MainWindow", u"Mask Options", None))
        self.bt_clr.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Brush radius", None))
        self.bt_undo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.ckb_protect.setText(QCoreApplication.translate("MainWindow", u"Protect", None))
        self.ckb_remove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.ckb_hremove.setText(QCoreApplication.translate("MainWindow", u"Seam removal horizontally", None))
        self.gb_seam.setTitle(QCoreApplication.translate("MainWindow", u"Seam Options", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Column", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Row", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.cmb_mode.setItemText(0, QCoreApplication.translate("MainWindow", u"Forward", None))
        self.cmb_mode.setItemText(1, QCoreApplication.translate("MainWindow", u"Backward", None))

        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Visualize", None))
        self.ckb_process.setText(QCoreApplication.translate("MainWindow", u"Process", None))
        self.ckb_energy_map.setText(QCoreApplication.translate("MainWindow", u"Energy Map", None))
        self.ckb_mask.setText(QCoreApplication.translate("MainWindow", u"Mask", None))
        self.ckb_all_seam.setText(QCoreApplication.translate("MainWindow", u"All Seam", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Information", None))
        self.lb_infor.setText(QCoreApplication.translate("MainWindow", u"Welcome to SeamCarving", None))
    # retranslateUi

